// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKVVe7n-65MeN8UuNlXeLQSxgPEu_KDd8',
    appId: '1:625898624603:web:65824b8b4e7a090b7c117e',
    messagingSenderId: '625898624603',
    projectId: 'ecoconnect-d2c03',
    authDomain: 'ecoconnect-d2c03.firebaseapp.com',
    storageBucket: 'ecoconnect-d2c03.appspot.com',
    measurementId: 'G-R4QVLFSVDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq01Pl8_Jzhi8JNVJURNxX1elXkbdvGzs',
    appId: '1:625898624603:android:37d74e7c86bc84eb7c117e',
    messagingSenderId: '625898624603',
    projectId: 'ecoconnect-d2c03',
    storageBucket: 'ecoconnect-d2c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhbzclBBuKX8cmPTlAcC3HMFzbglM0Sk',
    appId: '1:625898624603:ios:5586a87509e242317c117e',
    messagingSenderId: '625898624603',
    projectId: 'ecoconnect-d2c03',
    storageBucket: 'ecoconnect-d2c03.appspot.com',
    iosBundleId: 'com.example.ecoconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKVVe7n-65MeN8UuNlXeLQSxgPEu_KDd8',
    appId: '1:625898624603:web:03fe135c979e8a767c117e',
    messagingSenderId: '625898624603',
    projectId: 'ecoconnect-d2c03',
    authDomain: 'ecoconnect-d2c03.firebaseapp.com',
    storageBucket: 'ecoconnect-d2c03.appspot.com',
    measurementId: 'G-5FS0Y2KMYP',
  );
}
