name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.22.0-0.1.pre'  # Specify your Flutter version

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        publish_branch: master  # Change this to the branch you want to deploy to
